# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make dep
    - make gogenerate
env_files:
  # Work path :(
  github_token: "~/.outreach/github.token"
builds:
  - main: ./cmd/localizer
    id: &name localizer
    binary: *name
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives: []
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - '^(docs|test|build|chore)(\(.+?\))?:'
release:
  github:
    owner: jaredallard
    name: localizer
