name: Pull Request Shared Actions
on: pull_request

jobs:
  conventional_commit:
    name: Conventional Commit
    uses: getoutreach/actions/.github/workflows/conventional_commit.yaml@main
    secrets:
      OUTREACH_DOCKER_JSON: ${{ secrets.OUTREACH_DOCKER_JSON }}
